### ISSUE TITLE
application.yml doesn't support dubbo.protocol.port:  12345 (BUG)

### ISSUE THREAD

**Issue by jiaopy** [alibaba/dubbo#1462] opened 2018-03-13 10:12 UTC
in dubbo-spring-boot-sample-provider <version>0.1.0</version>
i alter application.properties to application.yml
then i find dubbo.protocol.port: 12345 is not supported ,the port will be 20880

**Comment by lovepoem** [comment] 2018-03-14 07:25
Duplicate of https://github.com/alibaba/dubbo/issues/1399

It is fixed in https://github.com/alibaba/dubbo/pull/1401   ，will be released in v2.6.1

**Closed by lovepoem** 2018-03-14 07:25 UTC
