### ISSUE TITLE
bug report:`duplicate service` warn on dubbo-admin

### ISSUE THREAD

**Issue by liulimin** [alibaba/dubbo#977] opened 2017-11-30 05:42 UTC
Lots of "The same service provided by two applications!" on the provider page.
This must be a displaying bug。
see also: http://blog.csdn.net/u012063409/article/details/59110559

**Comment by chickenlj** [comment] 2017-11-30 16:25
Duplicate of #714

**Comment by lovepoem** [comment] 2017-12-20 05:27
fixed in https://github.com/alibaba/dubbo/pull/780

**Closed by lovepoem** 2017-12-20 05:27 UTC
Labels: type/duplicate
