### ISSUE TITLE
application.yml doesn't support dubbo.protocol.port: 12346 （BUG）

### ISSUE THREAD

**Issue by jiaopy** [alibaba/dubbo#1418] opened 2018-03-05 03:09 UTC
在yml中dubbo.protocol.port的配置，修改端口号后还是取的默认的
在application.properties中配置就没事

**Comment by beiwei30** [comment] 2018-03-05 03:14
pls. attach a test case to reproduce the problem.

**Comment by lovepoem** [comment] 2018-03-05 03:15
Duplicate of alibaba/dubbo#1399

It is fixed in alibaba/dubbo#1401 ，will be released in next version

**Comment by jiaopy** [comment] 2018-03-05 03:23
About what time?

**Comment by chickenlj** [comment] 2018-03-05 03:31
@jiaopy Please subscribe to  dev@dubbo.apache.org, release plans will be published here.

**Comment by jiaopy** [comment] 2018-03-05 03:33
thanks

**Closed** 2018-03-06 12:09 UTC
